### ISSUE TITLE
round1の振り返り

### ISSUE THREAD

**Issue by KCN33** [gitpractice-enpit/tsukubaguide_5#4]
ブランチの削除がうまくいかないぞ

**Comment by naruwo-github** [comment]
勝手にマージしてごめんなさい。

**Comment by muratananaho** [comment]
ファイル名を間違えてアレヤコレヤしてたらmasterを変更してしまっったｿﾞ・・・・自分でやり直してマージ(プルリクエストのコンフリクトを解消し、追加)できたので申し訳ないがやってほしいｿﾞ

**Comment by muratananaho** [comment]
slackのDMでぐるーぷを

**Comment by yuyurun** [comment]
プッシュができない問題・・・進めなくてごめんなさい。
練習では、できたのにどうしよう。

**Comment by KCN33** [comment]
適当にslackに方針とか書いていったりするのでslack見てね
