### ISSUE TITLE
全体の振り返り

### ISSUE THREAD

**Issue by muratananaho** [gitpractice-enpit/tsukubaguide_5#7]

**Comment by KCN33** [comment]
round1しかできなかった
・とりあえずなんとなく流れはわかったような…
・Markdownをうまく使っていきたい

**Comment by muratananaho** [comment]
間違ってmasterを変更した時の復旧がスライドの最後の方にあったのに見てなかった。プルリクエストレビュー(コメント)される前に自分でmargeしないようにしたいと思った。

**Comment by yuyurun** [comment]
たくさんごめんなさい。ありがとう。
何回もやって慣れないといけないなと思った。

**Comment by naruwo-github** [comment]
僕も自分でmergeしてしまいました。
反省です、、、

**Comment by pyst1g** [comment]
まだ勉強不足で分からないことがたくさんあった。

**Comment by naruwo-github** [comment]
たっさん勉強しな！！

**Comment by yuyurun** [comment]
ファイルの名前を間違えるのも気をつけなきゃって思いました。

**Comment by muratananaho** [comment]
そう(大声)

**Comment by muratananaho** [comment]
あるある言いたい〜

**Comment by KCN33** [comment]
RG…
